// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRcco1Y4F36C432ofzU3sHAjdYtEYh6cs',
    appId: '1:155001957618:web:a483e643c027453f03f46b',
    messagingSenderId: '155001957618',
    projectId: 'ecommerceapp-f810d',
    authDomain: 'ecommerceapp-f810d.firebaseapp.com',
    storageBucket: 'ecommerceapp-f810d.appspot.com',
    measurementId: 'G-D8MR50XZBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWYKV0ad3yD--G0vYHOSEentd7BahJjkQ',
    appId: '1:155001957618:android:3e905996d61095c903f46b',
    messagingSenderId: '155001957618',
    projectId: 'ecommerceapp-f810d',
    storageBucket: 'ecommerceapp-f810d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb8KplJ8aNzd-d3BCamKLOaOJrQfY2peA',
    appId: '1:155001957618:ios:33f80ee802cac4db03f46b',
    messagingSenderId: '155001957618',
    projectId: 'ecommerceapp-f810d',
    storageBucket: 'ecommerceapp-f810d.appspot.com',
    androidClientId: '155001957618-ufa8qtpftir7jt58kf5e8avdmkrqs5t8.apps.googleusercontent.com',
    iosClientId: '155001957618-u27s0t72bb570g3nja8tdlib6lv5p2ae.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAdminPanel',
  );
}
